### test delete (disable csrf at security config to successfully delete)
DELETE localhost:8080/api/v1/user/delete/4

### test login (disable csrf at security config to successfully login)
POST localhost:8080/api/v1/user/login/auth
Content-Type: application/json

{
  "email": "raushanah_luomamt@voice.oh",
  "password": "lvG5wVN7z8Q8nMdzx"
}


